/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ModuloIdRouteImport } from './routes/modulo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloIdRoute = ModuloIdRouteImport.update({
  id: '/modulo/$id',
  path: '/modulo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/lancamentos': typeof LancamentosRoute
  '/modulos': typeof ModulosRoute
  '/radar': typeof RadarRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/lancamentos': typeof LancamentosRoute
  '/modulos': typeof ModulosRoute
  '/radar': typeof RadarRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/lancamentos': typeof LancamentosRoute
  '/modulos': typeof ModulosRoute
  '/radar': typeof RadarRoute
  '/modulo/$id': typeof ModuloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/historico' | '/lancamentos' | '/modulos' | '/radar' | '/modulo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/historico' | '/lancamentos' | '/modulos' | '/radar' | '/modulo/$id'
  id:
    | '__root__'
    | '/'
    | '/historico'
    | '/lancamentos'
    | '/modulos'
    | '/radar'
    | '/modulo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  LancamentosRoute: typeof LancamentosRoute
  ModulosRoute: typeof ModulosRoute
  RadarRoute: typeof RadarRoute
  ModuloIdRoute: typeof ModuloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$id': {
      id: '/modulo/$id'
      path: '/modulo/$id'
      fullPath: '/modulo/$id'
      preLoaderRoute: typeof ModuloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  LancamentosRoute: LancamentosRoute,
  ModulosRoute: ModulosRoute,
  RadarRoute: RadarRoute,
  ModuloIdRoute: ModuloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
